project:
  type: website


website:
  sidebar: false
  title: "SR-SAVI Conference"
  navbar:
    left:
      - href: index.qmd
        text: Welcome
      - href: program.qmd
        text: Program
      - href: speakers.qmd
        text: Speakers
      - href: about.qmd
        text: About

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

